from typing import Any, Protocol, Self


class Repository(Protocol):
    def get(self, kind: str, identifier: str, entity_type: type) -> Any: ...
    def list(self, kind: str, entity_type: type) -> list[Any]: ...
    def save(self, kind: str, entity: Any) -> None: ...


class UnitOfWork(Protocol):
    repository: Repository

    def enqueue(self, target: str, event_type: str, payload: dict) -> str: ...
    def seen(self, identifier: str) -> bool: ...
    def remember(self, identifier: str) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
