# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rental_runtime/proto/customers.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "rental_runtime/proto/customers.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$rental_runtime/proto/customers.proto\x12\x13rental.customers.v1")\n\x12\x45ligibilityRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t"C\n\x10\x45ligibilityReply\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07\x61llowed\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t2o\n\tCustomers\x12\x62\n\x10\x43heckEligibility\x12\'.rental.customers.v1.EligibilityRequest\x1a%.rental.customers.v1.EligibilityReplyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rental_runtime.proto.customers_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ELIGIBILITYREQUEST"]._serialized_start = 61
    _globals["_ELIGIBILITYREQUEST"]._serialized_end = 102
    _globals["_ELIGIBILITYREPLY"]._serialized_start = 104
    _globals["_ELIGIBILITYREPLY"]._serialized_end = 171
    _globals["_CUSTOMERS"]._serialized_start = 173
    _globals["_CUSTOMERS"]._serialized_end = 284
# @@protoc_insertion_point(module_scope)
